export const SIDEBAR_OPEN = 'SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'SIDEBAR_CLOSE'

export const SET_LOADING = 'SET_LOADING'

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const SET_USER = 'SET_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

// password
export const FETCH_PASSWORDS_SUCCESS = 'FETCH_PASSWORDS_SUCCESS'
export const FETCH_PASSWORDS_ERROR = 'FETCH_PASSWORDS_ERROR'

export const CREATE_PASSWORD_SUCCESS = 'CREATE_PASSWORD_SUCCESS'
export const CREATE_PASSWORD_ERROR = 'CREATE_PASSWORD_ERROR'
export const DELETE_PASSWORD_ERROR = 'DELETE_PASSWORD_ERROR'

export const FETCH_SINGLE_PASSWORD_SUCCESS = 'FETCH_SINGLE_PASSWORD_SUCCESS'
export const FETCH_SINGLE_PASSWORD_ERROR = 'FETCH_SINGLE_PASSWORD_ERROR'
export const EDIT_PASSWORD_SUCCESS = 'EDIT_PASSWORD_SUCCESS'
export const EDIT_PASSWORD_ERROR = 'EDIT_PASSWORD_ERROR'

// note
export const FETCH_NOTES_SUCCESS = 'FETCH_NOTES_SUCCESS'
export const FETCH_NOTES_ERROR = 'FETCH_NOTES_ERROR'

export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_ERROR = 'CREATE_NOTE_ERROR'
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR'

export const FETCH_SINGLE_NOTE_SUCCESS = 'FETCH_SINGLE_NOTE_SUCCESS'
export const FETCH_SINGLE_NOTE_ERROR = 'FETCH_SINGLE_NOTE_ERROR'
export const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS'
export const EDIT_NOTE_ERROR = 'EDIT_NOTE_ERROR'
